name: 'Timeweb Firewall'
description: 'Add current runner IP to a whitelist of the Timeweb firewall'
author: 'beholdr'

inputs:
  firewall:
    description: 'Firewall ID'
    required: true
  token:
    description: 'Timeweb API token'
    required: true
  protocol:
    description: 'Rule protocol'
    required: false
    default: 'tcp'
  port:
    description: 'Rule port'
    required: false
    default: '22'

runs:
  using: node20
  main: dist/index.js
  post: dist/index.js

branding:
  icon: 'unlock'
  color: 'blue'
